interface word {
	word: string;
	detail: string;
}

export const words: word[] = [
	{ word: "abissal", detail: "Profundidade extrema; insondável." },
	{ word: "abnegação", detail: "Renúncia de interesses pessoais em favor de outras pessoas; sacrifício." },
	{ word: "absurdo", detail: "Contrário à razão; sem lógica." },
	{ word: "acústica", detail: "Propriedades sonoras de um ambiente." },
	{ word: "afável", detail: "Que demonstra amabilidade; amigável." },
	{ word: "alabastro", detail: "Tipo de mineral translúcido." },
	{ word: "alcoviteiro", detail: "Indivíduo que se intromete na vida alheia; fofoqueiro." },
	{ word: "alocução", detail: "Discurso formal ou solene." },
	{ word: "amálgama", detail: "Mistura homogênea de diferentes elementos; combinação harmônica." },
	{ word: "ambivalente", detail: "Que possui sentimentos ou atitudes contraditórios em relação a algo." },
	{ word: "anátema", detail: "Algo ou alguém amaldiçoado; maldição." },
	{ word: "âmbito", detail: "Espaço ou campo de ação; abrangência." },
	{ word: "antípoda", detail: "Ponto diametralmente oposto na Terra." },
	{ word: "arbitrária", detail: "Que age de maneira subjetiva, sem seguir regras ou critérios definidos." },
	{ word: "assíduo", detail: "Que é constante, persistente; diligente." },
	{ word: "atroz", detail: "Cruel, horrendo; extremamente mau." },
	{ word: "autêntico", detail: "Genuíno, verdadeiro; que não é falso ou imitação." },
	{ word: "aviltante", detail: "Que humilha, degrada; que diminui o valor." },
	{ word: "belicoso", detail: "Que gosta de lutas ou guerras; agressivo." },
	{ word: "benevolente", detail: "Que age com bondade; benevolência." },
	{ word: "cacofonia", detail: "Combinação desarmônica de sons; dissonância." },
	{ word: "cacofônico", detail: "Que produz uma mistura desagradável de sons; estridente." },
	{ word: "caligrafia", detail: "Arte de escrever de maneira bonita e legível." },
	{ word: "capcioso", detail: "Que induz ao erro; enganoso." },
	{ word: "categórico", detail: "Que é claro, decisivo; inequívoco." },
	{ word: "circunlóquio", detail: "Uso excessivo de palavras; rodeio na expressão." },
	{ word: "coercitivo", detail: "Que impõe força, coerção; constrangedor." },
	{ word: "cognitivo", detail: "Relacionado ao conhecimento; processamento de informações." },
	{ word: "complacente", detail: "Que se mostra condescendente, tolerante; indulgente." },
	{ word: "concêntrico", detail: "Que tem o mesmo centro." },
	{ word: "concomitante", detail: "Que ocorre ao mesmo tempo; simultâneo." },
	{ word: "condescendente", detail: "Que age com indulgência, tolerância; benevolente." },
	{ word: "conspícuo", detail: "Que é notório, evidente; visível." },
	{ word: "contingente", detail: "Que é eventual, condicional; dependente de circunstâncias." },
	{ word: "convívio", detail: "Ato de viver em companhia; socialização." },
	{ word: "corroborar", detail: "Confirmar, validar; reforçar." },
	{ word: "deleterious", detail: "Que causa danos; prejudicial." },
	{ word: "demagogo", detail: "Político que utiliza de artifícios para ganhar popularidade; populista." },
	{ word: "dissensão", detail: "Desacordo, divergência; discórdia." },
	{ word: "efêmero", detail: "Que dura por pouco tempo; passageiro." },
	{ word: "eficaz", detail: "Que produz o efeito desejado; eficiente." },
	{ word: "egregious", detail: "Excepcionalmente ruim; flagrante." },
	{ word: "elocução", detail: "Modo de expressar-se oralmente; discurso." },
	{ word: "eloquente", detail: "Que se expressa de maneira persuasiva; convincente." },
	{ word: "emérito", detail: "Que é reconhecido por mérito; distinto." },
	{ word: "enigma", detail: "Coisa difícil de entender; mistério." },
	{ word: "entrelaçado", detail: "Que está entrelaçado, entrecruzado; conectado." },
	{ word: "equanimidade", detail: "Qualidade de manter a calma e a serenidade; tranquilidade." },
	{ word: "equivoco", detail: "Erro, engano; mal-entendido." },
	{ word: "esdrúxulo", detail: "Que tem acento na antepenúltima sílaba; fora do padrão." },
	{ word: "estupefaciente", detail: "Que causa estupor, atordoamento; narcótico." },
	{ word: "exacerbado", detail: "Que é levado ao extremo; exagerado." },
	{ word: "exímio", detail: "Que é muito habilidoso, perito; talentoso." },
	{ word: "exorbitante", detail: "Que ultrapassa limites; excessivo." },
	{ word: "expedito", detail: "Que é ágil, rápido; desembaraçado." },
	{ word: "extemporâneo", detail: "Que ocorre fora do tempo previsto; inoportuno." },
	{ word: "extrínseco", detail: "Que é externo; não inerente." },
	{ word: "fértil", detail: "Que produz abundância; fecundo." },
	{ word: "furtivo", detail: "Que age às escondidas; sorrateiro." },
	{ word: "genuíno", detail: "Que é autêntico, verdadeiro; legítimo." },
	{ word: "grandiloquente", detail: "Que se expressa de maneira pomposa; pretensioso." },
	{ word: "hipotético", detail: "Que é baseado numa hipótese; suposto." },
	{ word: "homologar", detail: "Aprovar, validar oficialmente; ratificar." },
	{ word: "ignóbil", detail: "Que é desprezível, infame; indigno." },
	{ word: "imbuir", detail: "Inspirar, impregnar; encher-se de." },
	{ word: "impávido", detail: "Que é destemido, corajoso; intrépido." },
	{ word: "implícito", detail: "Que está contido de forma não explícita; subentendido." },
	{ word: "imponente", detail: "Que impõe respeito; majestoso." },
	{ word: "incisivo", detail: "Que é cortante; que tem efeito decisivo." },
	{ word: "incólume", detail: "Que está ileso; sem ferimentos." },
	{ word: "indômito", detail: "Que é indomável; intratável." },
	{ word: "inebriante", detail: "Que causa embriaguez, êxtase; envolvente." },
	{ word: "inexorável", detail: "Que não se deixa persuadir; implacável." },
	{ word: "insipiente", detail: "Que é insosso; que falta sabor ou significado." },
	{ word: "insofismável", detail: "Que não permite dúvidas ou contestações; incontestável." },
	{ word: "intangível", detail: "Que não pode ser tocado; imaterial." },
	{ word: "intersticial", detail: "Que está situado entre outras coisas; ínterim." },
	{ word: "intransigente", detail: "Que não cede em seus princípios; inflexível." },
	{ word: "inusitado", detail: "Que é fora do comum; incomum." },
	{ word: "jactância", detail: "Exibição ostensiva de conquistas; ostentação." },
	{ word: "lânguido", detail: "Que demonstra cansaço; desanimado." },
	{ word: "lúgubre", detail: "Que é sombrio, triste; funesto." },
	{ word: "magnânimo", detail: "Que é generoso, nobre; benevolente." },
	{ word: "maledicência", detail: "Ato de falar mal de alguém; difamação." },
	{ word: "meritório", detail: "Que é digno de mérito; louvável." },
	{ word: "meticuloso", detail: "Que é cuidadoso nos detalhes; minucioso." },
	{ word: "modéstia", detail: "Qualidade de quem é humilde, discreto." },
	{ word: "mútuo", detail: "Que é reciproco; entre duas ou mais partes." },
	{ word: "nefasto", detail: "Que traz desgraça; funesto." },
	{ word: "obnubilar", detail: "Tornar obscuro, turvar; confundir." },
	{ word: "obsequioso", detail: "Que age com excessiva cortesia; servil." },
	{ word: "obstinação", detail: "Persistência excessiva em uma ideia; teimosia." },
	{ word: "onus", detail: "Encargo, ônus; responsabilidade." },
	{ word: "paradigma", detail: "Modelo ou padrão exemplar; referência." },
	{ word: "paradoxal", detail: "Que apresenta uma contradição aparente; paradoxo." },
	{ word: "plenipotenciário", detail: "Que possui plenos poderes; representante diplomático." },
	{ word: "preâmbulo", detail: "Introdução; parte inicial de um texto." },
	{ word: "prognóstico", detail: "Previsão do que pode acontecer; prognose." },
	{ word: "prolixo", detail: "Que é excessivamente longo; verborrágico." },
	{ word: "quimérico", detail: "Que é fantasioso, ilusório; irrealizável." },
	{ word: "quixotesco", detail: "Que é idealista a ponto de ser impraticável; sonhador." },
	{ word: "ratificar", detail: "Confirmar, validar; reafirmar." },
	{ word: "reiterar", detail: "Repetir, insistir; enfatizar." },
	{ word: "resiliente", detail: "Que tem a capacidade de se recuperar; resistente." },
	{ word: "reticente", detail: "Que é reservado, hesitante; que não revela completamente seus pensamentos." },
	{ word: "sagaz", detail: "Que é perspicaz, astuto; esperto." },
	{ word: "sanção", detail: "Ato de aprovar ou punir; penalidade." },
	{ word: "saudosista", detail: "Que sente saudades do passado; nostálgico." },
	{ word: "sibilante", detail: "Que produz som semelhante a um sibilo; assobiante." },
	{ word: "sagacidade", detail: "Qualidade de quem é sagaz; perspicácia." },
	{ word: "sustentáculo", detail: "Apoio ou suporte; sustento." },
	{ word: "tácito", detail: "Que é implicitamente entendido; não expresso explicitamente." },
	{ word: "tenaz", detail: "Que é persistente, obstinado; firme." },
	{ word: "tênue", detail: "Que é muito fino, delicado; sutil." },
	{ word: "ubíquo", detail: "Que está em todos os lugares ao mesmo tempo; onipresente." },
	{ word: "usurpar", detail: "Tomar posse de algo ilegalmente; apropriar-se indevidamente." },
	{ word: "vacilar", detail: "Demonstrar hesitação; oscilar." },
	{ word: "vagabundo", detail: "Que não tem moradia fixa; errante." },
	{ word: "venerar", detail: "Tratar com reverência; adorar." },
	{ word: "veraz", detail: "Que é verdadeiro, honesto; verídico." },
	{ word: "volúvel", detail: "Que muda facilmente de opinião ou humor; inconstante." },
	{ word: "voraz", detail: "Que devora com avidez; insaciável." },
	{ word: "zen", detail: "Relacionado ao budismo zen; estado de tranquilidade e meditação." },
];
